services:
  http_server:
    image: nginx:1.27.1-bookworm-otel
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./http_server/templates:/etc/nginx/templates
      - ./http_server/cert:/etc/ssl/certs
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      miumgnet:
        ipv4_address: 172.19.0.3
    
  ftp_server:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - 21000-21010:21000-21010
    environment:
      - USERS=one|asdag436tyaw34ga|/home/one/dir
      - ADDRESS=ftp.miumg-net.io
      - TLS_CERT=/home/one/certs/miumg-net.io.pem
      - TLS_KEY=/home/one/certs/miumg-net.io-key.pem
    volumes:
      - ./.shared/ftp:/home/one/dir
      - ./http_server/cert:/home/one/certs:ro
    networks:
      - miumgnet

  dns_server:
    image: ubuntu/bind9
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      - BIND9_USER=root
      - TZ=UTC
    volumes:
      - ./dns_server/named.conf.options:/etc/bind/named.conf.options
      - ./dns_server/named.conf.local:/etc/bind/named.conf.local
      - ./dns_server/db.miumg-net.io:/etc/bind/zones/db.miumg-net.io
      - ./.shared/cache_bind:/var/cache/bind
    user: root
    networks:
      miumgnet:
        ipv4_address: 172.19.0.4

networks:
  miumgnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/16
         gateway: 172.19.0.1
    